[package]
name = "hole"
version = "0.1.0"
authors = ["horhik <horhik@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntru = "0.5.6"
rusqlite = "0.24.0"
toml = "0.5.6"
